"""
PROVIDES COMPANY ALIASES IN ORDER TO CLEAN WHILE CREATING
THE CLEAN ENERGY REPORT
THIS FILE IS REQUIRED
"""

CONTRACTOR_COMPANIES = {
    'Absolutely Energized': 'Absolutely Energized Solar',
    'Trinity Hea': 'Trinity Solar',
    'Trinity Services': 'Trinity Services',
    'Trinity Solar': 'Trinity Solar',
    'Geogenix': 'Geogenix',
    '1st light': '1st Light Energy',
    'Mak': 'Mak Technologies',
    'BP': 'BP Solar International',
    'SunPower Capital': 'SunPower Capital',
    'SunPower Corp': 'SunPower Corporation',
    'Solar Landscape': 'Solar Landscape',
    'RCL Solar': 'RCL Solar',
    'Paladin Solar': 'Paladin Solar',
    'Orbit Energy': 'Orbit Energy',
    'Onforce': 'Onforce Solar',
    'National Energy P': 'National Energy Partners',
    'Morgan Solar': 'Morgan & Morgan Solar',
    'Lucent': 'Lucent Energy Management',
    'Independence': 'Independence Solar',
    'Independent': 'Independent Solar',
    'HESP C': 'HESP Construction',
    'HESP S': 'HESP Solar',
    'Heat Shed': 'Heat Shed',
    'Group Solar': 'Group Solar',
    'Grid Alternative': 'Grid Alternatives',
    'Grid Rev': 'Grid Revolution Solar',
    'Gridpoint': 'Gridpoint Services',
    'Grid Holding': 'Urban Grid Holdings',
    'Green Hybrid': 'Green Hybrid Energy Solutions',
    'Green Energy Con': 'Green Energy Construction & Consulting',
    'Evergreen Energy': 'Evergreen Energy',
    'First Power': 'First Power & Light',
    'Eastern Energy': 'Eastern Energy Services',
    'Dynamic Energy': 'Dynamic Energy',
    'Tesla': 'Tesla',
    'Vivint': 'Vivint',
    'Sunrun': 'Sunrun',
    'NRG': 'NRG',
    'Acos': 'ACOS',
    'Advanced Solar Product': 'Advanced Solar Products',
    'Advanced Renew': 'Advanced Renewable Solutions',
    'Ecological': 'Ecological Systems',
    'Alteris': 'Alteris Renewables',
    'Surewave': 'Surewave Solar',
    'Whitman': 'Whitman Construction',
    'Amergy': 'Amergy Solar',
    'Aston Solar': 'Aston Solar',
    'Bowman Walker': 'Bowman Walker Construction',
    'Castle Energy': 'Castle Energy',
    'Ad Energy': 'Ad Energy',
    'Amberjack': 'Amberjack Solar',
    'Aztec': 'Aztec Solar',
    'Bap': 'BAP Power Corporation',
    '1st US': '1st US Energy',
    'Adema': 'Adema Technologies',
    'Allied Con': 'Allied Construction',
    'Momentum Solar': 'Momentum Solar',
    'My NJ Solar': 'NJ Solar Power',
    'NJ Solar Solutions': 'NJ Solar Solutions',
    'Powerlution': 'Powerlutions',
    'R U Bright': 'R U Bright',
    'Ray Angelini': 'Ray Angelini',
    'Arosa': 'Arosa Solar',
    'Breaker Electric': 'Breaker Electric',
    'Code Green': 'Code Green',
    'Sunvest Solar': 'SunVest Solar',
    'Sungevity': 'Sungevity',
    'The Solar Center': 'Solar Center',
    'Samba Energy': 'Samba Energy',
    'Tonetta Electrical': 'Tonetta Electrical Contractor',
    'US Clean Energy': 'US Clean Energy',
    'Spectrum Energy': 'Spectrum Energy',
    'Solar Spectrum': 'Solar Spectrum',
    'Solar Home': 'Solar Home',
    'Skyline Solar': 'Skyline Solar',
    'Statewide Solar': 'Statewide Solar',
    'Astrum': 'Astrum Solar',
    'Eznergy': 'Eznergy',
    'Four Point': 'Four Point',
    'Geoscape': 'Geoscape',
    'Green Power Energy': 'Green Power Energy',
    'Green Power Solution': 'Green Power Solution',
    'Jersey Solar': 'Jersey Solar',
    'Kaitanna': 'Kaitanna Solar',
    'Kopp Electric': 'Kopp Electric',
    'Mercury Solar System': 'Mercury Solar Systems',
    'NJR Home': 'NJR Home Services',
    'NJRClean': 'NJRClean Energy Ventures Corp',
    'Rec Solar': 'Rec Solar',
    'Reliable Power': 'Reliable Power & Solar',
    'Roof Diagnostics': 'Roof Diagnostics',
    'Solar Energy World': 'Solar Energy World',
    'Helios Solar Energy': 'Helios Solar Energy',
    'Solular': 'Solular',
    'Sun Up': 'Sun Up Zero Down',
    'Moore Energy': 'Moore Energy',
    'Meridian Property': 'Meridian Property Services',
    'Kiss': 'Kiss Electric',
    'JRC Construction': 'JRC Construction',
    'ASC Solar': 'ASC Solar Solutions',
    'Alien Fuel': 'Alien Fuel',
    'Dobtol': 'Dobtol Construction',
    'ECS': 'ECS Energy',
    'Energy Solutions of New Jersey': 'Energy Solutions of New Jersey',
    'Evoke': 'Evoke Solar',
    'Green Cities': 'Green Cities Energy',
    'Green Sun': 'Green Sun Energy',
    'Ocean Solar': 'Ocean Solar',
    'P3 Integration': 'P3 Integration',
    'Purharvest Energy': 'Purharvest Energy',
    'Power Installs': 'Power Installs',
    'Ryan Inc': 'Ryan Inc',
    'Safari Energy': 'Safari Energy',
    'Shore Green Energy': 'Shore Green Energy',
    'ISI Solar': 'ISI Solar',
    'Solar Energy Is Power': 'Solar Energy Is Power',
    'Sun Saver': 'Sun Saver Solar Systems',
    'Sundurance': 'Sundurance Energy',
    'Sunshine Solar': 'Sunshine Solar Systems',
    'Solar Advantage': 'Solar Advantage',
    'Accord Power': 'Accord Power',
    'Geopeak': 'GeoPeak Energy',
    'Go Solar Electric': 'Go Solar Electric',
    'Suntuity': 'Suntuity',
    'Infinity Solar': 'Infinity Solar Systems',
    'Vanguard': 'Vanguard Energy Partners',
    'Genrenew': 'GenRenew LLC',
    'Direct Energy Solar': 'Direct Energy Solar',
    'Powell Energy': 'Powell Energy and Solar',
    'Sundial Solar': 'Sundial Solar Innovations',
    'Impact': 'Impact Solar',
    'Greentech': 'Greentech Solar USA LLC',
    'Grid Revolu': 'Grid Revolution Solar',
    'Panatec': 'Panatech Corporation',
    'Azimuth': 'Azimuth Renewable Energy'
}

AND_CONTRACTOR_COMPANIES = {
    'Patel Builders': ['Patel', 'Builder'],
    'RCL Enterprises': ['RCL', 'terprise'],
    'Morgan Associates': ['Morgan', 'Associates'],
    'George J Keller & Sons': ['Keller', 'Son'],
    'Trinity Solar': ['Trinity', 'Solar'],
    'Tesla': ['Sola', 'City'],
    'All Season Solar': ['All', 'Season'],
    'Sea Bright Solar': ['Sea', 'Bright'],
    'Advanced Solar & Energy Solutions': ['Advanced Solar', 'Solution'],
    'East Coast Solar': ['East', 'Coast'],
    'Paradise Solar': ['Paradise', 'Solar'],
    'Paradise Energy Solutions': ['Paradise', 'Energy'],
    'Amped On Solar': ['Amped', 'Solar'],
    'Nova Alternative Energy Solutions': ['Nova', 'Alternative'],
    'Alternative Electric': ['Alternative', 'Electric'],
    'A Clear Alternative': ['Clear', 'Alternative'],
    'Clear Skies Solar': ['Clear', 'Ski'],
    'NJ Solar Power': ['NJ Solar', 'Power'],
    'American Renewable Energy': ['American', 'Renewable'],
    'Momentum Solar': ['Momentum', 'Solar'],
    'Self Install': ['Self', 'Install'],
    'LB Electric': ['LB', 'Electric'],
    'KG Solar & Renewable Energy': ['KG Solar', 'Renewable'],
    'Enter Solar': ['Enter', 'Solar'],
    'Green Point Energy': ['Green', 'Point'],
    'OneRoof Energy': ['One', 'Roof'],
    'Pro-Tech Energy Solutions': ['Pro', 'Tech'],
    'Pfister Energy': ['Pfister', 'Energy'],
    'Pfister Maintenance': ['Pfister', 'Maintenance'],
    'SunnyMac': ['Sunny', 'Mac'],
    'Greenhouse Solar': ['Green', 'House']
}

OR_CONTRACTOR_COMPANIES = {
    'G&S Solar Installers': ['G \+ S', 'G&S'],
    'Miller Brothers': ['301 Al', 'Miller Bro'],
    'ACE Solar': ['Alliance Coop', 'Ace Solar']
}
